### PR TITLE
include required "align.h" header in makefile builds

### LINKED ISSUE #13: align.h missing from bin directory
The `align.h` header needed by `KangarooTwelve.h` is missing from the bin directory after running make.

Example:

```
make generic64/libk12.so
ls -1 bin/generic64/libk12.so.headers/
```

Output:
```
config.h
KangarooTwelve.h
KeccakP-1600-SnP.h
```

### PR DESCRIPTION
**Pull request by mumbleskates**
fixes #13, i think

### CODE REVIEW

**Comment by mumbleskates** [comment]
it works when i do it.

**Comment by gvanas** [comment]
Thanks, but I think it would be better to make the different targets inherit from the "common" fragment.

**Comment by mumbleskates** [comment]
@gvanas I thought about that and looked into it, but decided against it at first try since that file is not actually referenced by either of the public headers: it is only used by the implementations that end up in the library file. When put into the public `include` folder, it is dead code.

Looking around it seems like the "common" fragment is only used by "K12Tests"? Maybe we should get rid of it instead, or refactor it to be and contain something more descriptive (such as "public headers").

**Comment by gvanas** [comment]
You're right. The core issue is, I think, that the the `<h>` tags do not distinguish between the header files that are necessary for compiling and those that are to be moved to the public `include` folder. Something to improve in the build system…

**Pull request merged**
